sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Xzy2002..

  alioss:
      endpoint: oss-cn-shanghai.aliyuncs.com
      access-key-id: LTAI5t7s4ep5aa9BhZXQBmqY
      access-key-secret: DqTPbzGLbxKefm9IbFza6X1im7Bm8P
      bucket-name: sky-take-out-ziy

  redis:
      host: localhost
      port: 6379
      password: "Xzy2002.."
      database: 10

  wechat:
      appid: wxd92a3e1fa38c0779
      secret: 8fa4ddfcc53f72850f5d096b8f70bb9d
